name    'naturalis-monophylizer'
version '0.0.1'
author 'pgomersbach'
license 'Apache License, Version 2.0'
summary 'Puppet module to install the monophylizer webtool'
description 'Puppet module to install the monophylizer webtool. For more information using this tool: https://github.com/naturalis/monophylizer'
project_page 'https://github.com/naturalis/puppet-monophylizer'
dependency 'puppetlabs-apache', '>= 0.6.0'
dependency 'example42-perl', '>= 2.0.10'
dependency 'puppetlabs/vcsrepo, '>= 0.1.1'
